spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop #MVCC = true 기능이 자동추가 됨
    username: sa
    password: 1248
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 1.table drop 2.table create
    properties:
      hibernate:
#        show_sql: true # jpa나 hibernate가 생성하는 sql을 system out을 통해 출력
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # jpa나 hibernate가 생성하는 sql을 logger를 통해 출력
    org.hibernate.type: trace #query log를 찍어줌, sql 실행 파라미터를 로그로 남김
